# Generated by Django 2.2.19 on 2022-09-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название товара', max_length=100, verbose_name='Название')),
                ('description', models.TextField(help_text='Описание товара', verbose_name='Описание')),
                ('price', models.PositiveIntegerField(help_text='Стоимость товара', verbose_name='Стоимость')),
            ],
        ),
    ]
