# Generated by Django 2.2.19 on 2022-09-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Стоимость товара', max_digits=6, verbose_name='Стоимость'),
        ),
    ]
