# Generated by Django 2.2.19 on 2022-09-12 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220912_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Количество товаров')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='backend.Item', verbose_name='Товар')),
            ],
        ),
    ]
