# Generated by Django 2.2.19 on 2022-09-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
